# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8758b7b93d2d1ba3fc667d08a2e101485695f03120930d524a92ecbcb3535c818921f5e52d7202734534513a819038dbd400ac7ab2ef0b4db48fd4434e0ee00

test:
  secret_key_base: 8cd98ac6bbc48ab38bf29ca9b57c0f44370272590d5019af097532723f7d8599acb801dc4b8b8f36e342f80424f966b5b03afa6526f2b8bc2d659043987c3773

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
